### INDEX

GET http://localhost:3000/products.json
Content-Type: application/json

### CREATE

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "hat", 
  "price": "15", 
  "image_url": "https://i5.walmartimages.com/asr/4626dbee-c555-4c70-a86d-9c965710b99f_1.563c198cddc9f4f0fd3180366552bae9.jpeg?odnHeight=612", 
  "description": "goes on your head"
}

### SHOW
GET http://localhost:3000/products/7.json
Content-Type: application/json


### UPDATE
PATCH http://localhost:3000/products/7.json
Content-Type: application/json

{
  "name": "dress"
}

### DESTROY

DELETE http://localhost:3000/products/8.json
Content-Type: application/json

###

#POST http://localhost:3000/body_params/
#content-type: application/json

#{
 # "data": "data"
#}

###