### INDEX_PRODUCTS

GET http://localhost:3000/products.json
Content-Type: application/json

### CREATE_PRODUCTS

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "water bottle", 
  "price": "20", 
  "image_url": "https://www.target.com/p/simple-modern-32-oz-stainless-steel-summit-water-bottle-with-straw-lid/-/A-80585632#", 
  "description": "stores liquid"
}

### SHOW_PRODUCTS
GET http://localhost:3000/products/7.json
Content-Type: application/json


### UPDATE_PRODUCTS
PATCH http://localhost:3000/products/7.json
Content-Type: application/json

{
  "name": "dress"
}

### DESTROY_PRODUCTS

DELETE http://localhost:3000/products/8.json
Content-Type: application/json

### INDEX_SUPPLIERS

GET http://localhost:3000/suppliers.json
Content-Type: application/json

### CREATE_SUPPLIERS

POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "", 
  "email": "", 
  "phone_number": ""
}

### SHOW_SUPPLIERS
GET http://localhost:3000/suppliers/7.json
Content-Type: application/json


### UPDATE_SUPPLIERS
PATCH http://localhost:3000/suppliers/7.json
Content-Type: application/json

{
  "name": ""
}

### DESTROY_SUPPLIERS

DELETE http://localhost:3000/suppliers/8.json
Content-Type: application/json

