### INDEX_PRODUCTS

GET http://localhost:3000/products.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

### CREATE_PRODUCTS

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "water bottle", 
  "price": "20", 
  "image_url": "https://www.target.com/p/simple-modern-32-oz-stainless-steel-summit-water-bottle-with-straw-lid/-/A-80585632#", 
  "description": "stores liquid"
}

### SHOW_PRODUCTS
GET http://localhost:3000/products/7.json
Content-Type: application/json


### UPDATE_PRODUCTS
PATCH http://localhost:3000/products/7.json
Content-Type: application/json

{
  "name": "dress"
}

### DESTROY_PRODUCTS

DELETE http://localhost:3000/products/8.json
Content-Type: application/json

### INDEX_SUPPLIERS

GET http://localhost:3000/suppliers.json
Content-Type: application/json

### CREATE_SUPPLIERS

POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "", 
  "email": "", 
  "phone_number": ""
}

### SHOW_SUPPLIERS
GET http://localhost:3000/suppliers/7.json
Content-Type: application/json


### UPDATE_SUPPLIERS
PATCH http://localhost:3000/suppliers/7.json
Content-Type: application/json

{
  "name": ""
}

### DESTROY_SUPPLIERS

DELETE http://localhost:3000/suppliers/8.json
Content-Type: application/json

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John",
  "email": "john@example.com",
  "password": "passwordd",
  "password_confirmation": "passwordd"
}
### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
### Photos create
POST http://localhost:3000/index
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "product_id": ,
  "url": ""
}

### CREATE_order

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNzQ5MjB9.otdf1Yke8QvphapjPLNo1nHCYzQZ57IbdNNR6ei5YwQ

{
  "product_id": 4, 
  "quantity": 1
}

### SHOW_orders
GET http://localhost:3000/orders/6.json
Authorization: Bearer 
Content-Type: application/json

### INDEX_orders

GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNzQ5MjB9.otdf1Yke8QvphapjPLNo1nHCYzQZ57IbdNNR6ei5YwQ
Content-Type: application/json
